### ISSUE TITLE
Missing Pagination

### ISSUE THREAD

**Issue by zhaolinlau** [pulsar-edit/package-frontend#111]
### Thanks in advance for your bug report!

- [X] Have you reproduced this issue in incognito/private browsing?
- [X] Have you made sure you issue doesn't already exist?

### Where is the URL that this occurs?

https://web.pulsar-edit.dev/packages

### What's your issue?

The pagination is missing.

![image](https://github.com/pulsar-edit/pulsar-edit.github.io/assets/68846168/a8dc51a4-d906-4f4f-bb49-6de721394058)

**Comment by confused-Techie** [comment]
I've gone ahead and transferred this issue to the correct repository
