### ISSUE TITLE
Add sorting options when searching for packages

### ISSUE THREAD

**Issue by IowU** [pulsar-edit/package-frontend#119]
### Have you checked for existing feature requests?

- [X] Completed

### Summary

Hello,
It would be useful to add sorting options when displaying the packages on the Website (like sorting by number of downloads, stars ecc).

Not sure if this requests falls under the [https://github.com/pulsar-edit/package-frontend/issues/48](https://github.com/pulsar-edit/package-frontend/issues/48)

### What benefits does this feature provide?

Better searching experience

### Any alternatives?

no

**Comment by confused-Techie** [comment]
Thanks a ton for contributing!

But yes you are right that #48 is the same issue request, with #118 being the implementation of this.

So feel free to comment on that issue any thoughts that you may have, as it's still being reviewed to be merged in

**Comment by IowU** [comment]
Ok thanks, I missed that PR. I'm closing this issue.
