### ISSUE TITLE
Expose more service metadata

### ISSUE THREAD

**Issue by savetheclocktower** [pulsar-edit/package-frontend#124]
### Have you checked for existing feature requests?

- [X] Completed

### Summary

One thing we should do to improve the “IDE story” is to surface the concept of _services_ to users.

What we seem not to want to do: “Here is a monolithic package that installs a bunch of stuff you don't understand.”

What we should probably do instead: “The `ide-typescript` package provides these _services_; let's help you find packages to consume them.”

Two obvious improvements:

### Tell users when they're searching for service consumers/providers

The `service` and `serviceType` search params are useful, but a search results page that uses those params doesn't have anything on the page to distinguish it from an ordinary package listing. Here's how we could fix that:

<img width="1110" alt="Screen Shot 2023-12-26 at 3 41 46 PM" src="https://github.com/pulsar-edit/package-frontend/assets/3450/9833bc71-290b-43b5-bcb0-fc0b9b3d62e6">

(Through working on this, I discovered pagination counts are wrong; filed [this issue](https://github.com/pulsar-edit/package-backend/issues/213).)

### Tell users when a package consumes/provides services

On a package detail page, we can enumerate the services provided and consumed. For instance, if a package **provides** the `foo` service, `foo` would be a link to a search results page that filters on packages that **consume** `foo`.

A couple ways we could present this:

<img width="1154" alt="Screen Shot 2023-12-26 at 3 09 07 PM" src="https://github.com/pulsar-edit/package-frontend/assets/3450/d70a1f69-6d89-40dd-82ca-b70725c56e1f">
<img width="1153" alt="Screen Shot 2023-12-26 at 3 08 44 PM" src="https://github.com/pulsar-edit/package-frontend/assets/3450/4b6d6c6d-1518-4112-bd26-5cda52f418fc">

### What benefits does this feature provide?

Explained above.

### Any alternatives?

No, I think this is the best option. We want to be able to tell users “here's how you can do X” without privileging one particular package over others. “Here are all packages that can do X” is a good way of doing that. The user can make judgments based on download counts, on the presence of “Made for Pulsar!” badges, or whatever else.

**Comment by confused-Techie** [comment]
@savetheclocktower Thanks for contributing over on this repo!

Overall, this is a fantastic suggestion, and I really like the way your made the mockup for the sidebar here, which I honestly think should be the way we go about adding this new information.

Plus, it'd be a great idea to expose the ability for users to actually search for these parameters, although the search on the website is still lacking, so maybe that isn't the highest priority.

If you have the mockup HTML to share that'd be rad, otherwise I'll take a look at implementing this sidebar, unless anyone beats me too it, thanks!

**Comment by savetheclocktower** [comment]
I'll open the PR today.
