### ISSUE TITLE
Create a Simple User Data Page

### ISSUE THREAD

**Issue by confused-Techie** [pulsar-edit/package-frontend#16]
### Have you checked for existing feature requests?

- [X] Completed

### Summary

One last step before we enable authentication on the backend, is we need to the landing page after signing up for a Pulsar User Account. Where most importantly a user is able to grab their API key to the Pulsar Backend.

I've asked on the Discord for any assistance with this and will ping the relevant respondents.

Speaking of which I can't assign you on here for some reason so @JamieStack

---

This user page should really just be vanilla CSS and vanilla HTML or if you'd like EJS. Don't worry about collecting the user data at this time, simply creating a place for it to go within `ejs-views/user_page.ejs` on the `login-user-features` branch.

Feel free to submit a PR directly to this branch or commit directly into it and just let me know.

This user page should be able to display the following details: (In order of importance)

* The Users API Token, ideally with a button to copy right next to it
* The Users Username
* The Users Avatar, this will be a link to their GitHub avatar, and as such can just by a smaller img on the page 
* The Timestamp of when the user account was created.

Like I said this doesn't need to be anything to fancy, just enough to make the information consumable by end users, until the frontend sees more significant upgrades

### Enter your response below:

This is needed to allow a good user experience during sign up

### Any alternatives?

Return JSON directly from the backend and make users figure it out

### Other examples:

Thanks for any assistance possible!

**Comment by JamieBradders** [comment]
Hey @confused-Techie - I can make a start on this for you 😄 I'll probably start digging around with it tomorrow evening (UK Time).

**Comment by confused-Techie** [comment]
> Hey @confused-Techie - I can make a start on this for you 😄 I'll probably start digging around with it this evening (UK Time).

Thanks so much, appreciate you taking the time to look at this one

**Comment by JamieBradders** [comment]
Referencing the PR to `login-user-features` from earlier today https://github.com/pulsar-edit/package-frontend/pull/19
