### ISSUE TITLE
Repeated Crashes in Prod due to being within a read only filesyste

### ISSUE THREAD

**Issue by confused-Techie** [pulsar-edit/package-frontend#28]
### Thanks in advance for your bug report!

- [X] Have you reproduced this issue in incognito/private browsing?
- [X] Have you made sure you issue doesn't already exist?

### Where is the URL that this occurs?

https://web.pulsar-edit.dev/**

### What's your issue?

The frontend is hosted in an environment with a read only filesystem.

What this means is that in our startup scripts we specify to run a `tailwind` script that attempts to write a file. This repeatedly fails to save the file on exit causing it to crash after each web request. Unsure of how it's serving the compiled CSS anyway, but likely this script should be moved to a postinstall stage, or a manual build script.

The dev portion of scripts can be left as is for improved developer experience, but prod can't run these scripts.

Additionally something else that will be solved by this, using tailwind in the frontend seems to take just enough ram (or some other newer process) that we are failing to deliver social media cards about 90% of the time. Since already we were very close to our memory limit during this process and would fail about 50% of the time.

I'm hoping solving the tailwind in prod can resolve this issue but time will tell.

@kyjus25 If you'd like to take a look, otherwise I will as soon as I can 

### Which OS/Browser/Version does this happen on?

N/A

### Steps to Reproduce/Additional Details:

N/A

**Comment by kyjus25** [comment]
> Unsure of how it's serving the compiled CSS anyway

It takes the source `/src/site.css` file and builds it to `./public/site.css` which is what the HTML loads in.

>  likely this script should be moved to a postinstall stage

Done in #29. I hope that fixes it! Worse case scenario we can unignore the `./public/site.css` file and commit it to git so prod doesn't have to do building it all, but it should work as postinstall since it does some puppeteer stuff already.

**Comment by confused-Techie** [comment]
Yeah great point on adding it to postInstall. I'll try to test this today, so otherwise we can unignore it
