### ISSUE TITLE
Accessibility: Package description text contrast is very low for dark themes

### ISSUE THREAD

**Issue by SunderB** [pulsar-edit/package-frontend#38]
### Thanks in advance for your bug report!

- [X] Have you reproduced this issue in incognito/private browsing?
- [X] Have you made sure you issue doesn't already exist?

### Where is the URL that this occurs?

https://web.pulsar-edit.dev/

### What's your issue?

The text contrast for the package description text when using the GitHub Dark and Dracula themes are very low:
GitHub Dark - 2.50
![image](https://user-images.githubusercontent.com/20426079/209952451-72fb318c-dae3-4989-8745-580aa254e41b.png)

Dracula - 1.88
![image](https://user-images.githubusercontent.com/20426079/209951729-95e7f454-7240-4183-9d8b-8b7712922434.png)

It seems from the HTML code that the colours are currently hardcoded via the tailwind class `text-gray-600` instead of being set by the theme. Perhaps this should be changed to a slightly lighter colour?

### Which OS/Browser/Version does this happen on?

Firefox on Windows 10

**Comment by confused-Techie** [comment]
Thanks for contributing with a bug report! I'll check this out as soon as I can!
