### ISSUE TITLE
[bug] Package page loading slowdowns

### ISSUE THREAD

**Issue by Spiker985** [pulsar-edit/package-frontend#4]
It appears that when loading package pages there is a rather large amount of time spent waiting. Looking at the performance analyzer within Firefox, this appears to possibly be a compound slowdown due to html rendering + image fetching.

In some instances it looks like it may be due to the resolution speed of the GitHub APIs themselves. I had several `github.com/path/to/file/raw/filename.ext` URLs, which get transposed to `raw.githubusercontent.com/path/to/file/filename.ext` take an eternity to load (legitimately 120 seconds for one of the platformio-ide-terminal gifs)

https://web.pulsar-edit.dev/packages/gitmoji-atom
![image](https://user-images.githubusercontent.com/7829451/199908700-5d786c11-8404-4395-a9f2-81a8ab1ecec4.png)
![image](https://user-images.githubusercontent.com/7829451/199908960-f255ebaf-7cc9-4212-a40c-6104f82b710f.png)

https://web.pulsar-edit.dev/packages/platformio-ide-terminal
![image](https://user-images.githubusercontent.com/7829451/199908625-aa021a51-9379-4071-8828-47c1b6cd4a1e.png)
![image](https://user-images.githubusercontent.com/7829451/199909550-6d1b59bd-8af1-45e1-a5c7-f4f4328b57a2.png)

https://web.pulsar-edit.dev/packages/chlorine
![image](https://user-images.githubusercontent.com/7829451/199908679-4d761135-e381-4e09-a4a8-df0a782a8ac0.png)
![image](https://user-images.githubusercontent.com/7829451/199909662-9337449f-85c1-42f2-a866-b579309bdbd0.png)

**Comment by kyjus25** [comment]
@confused-Techie @Spiker985 Can this be closed or what is the recommended action to resolve this?

**Comment by Spiker985** [comment]
Presumably, the caching is now doing its job and we can close it.

I should be able to reload those pages with Firefox to see if there are still slowdowns or not

**Comment by confused-Techie** [comment]
Based on above comments, I'll go ahead and close this one.

It can always be reopened if needed
