### ISSUE TITLE
Code snippets unreadable in default (Atom.io) theme

### ISSUE THREAD

**Issue by AlexWayfer** [pulsar-edit/package-frontend#59]
### Thanks in advance for your bug report!

- [X] Have you reproduced issue in [safe mode](https://pulsar-edit.dev/docs/atom-archive/faq/sections/what-does-safe-mode-do.html)?
- [X] Have you used the [debugging guide](https://pulsar-edit.dev/docs/atom-archive/hacking-atom/#debugging) to try to resolve the issue?
- [X] Have you checked our [FAQs](https://pulsar-edit.dev/docs/launch-manual/sections/faq/) to make sure your question isn't answered there?
- [X] Have you checked to make sure your issue does not already [exist](https://github.com/issues?q=is%3Aissue+user%3Apulsar-edit+is%3Aopen)?
- [X] Have you checked you are on the latest release of Pulsar?

### What happened?

The colors in code snippets are broken in the default theme (Atom.io).

### Pulsar version

Website

### Which OS does this happen on?

🐧 Arch based (Manjaro, Garuda, etc.)

### OS details

Doesn't matter I believe

### Which CPU architecture are you running this on?

None

### What steps are needed to reproduce this?

1. Go to a package with code block in README.

### Additional Information:

![image](https://user-images.githubusercontent.com/6510020/216398580-551e3aa4-9b84-4429-8cb8-97282f98e49a.png)

![image](https://user-images.githubusercontent.com/6510020/216398692-626cae17-85ec-4f12-b31b-86b67811b649.png)

https://web.pulsar-edit.dev/packages/x-terminal

**Comment by Daeraxa** [comment]
> Also I'd like to see a separate issue template for frontend repo, excluding "latest release" and "safe mode" checkmarks for the application.

We have a separate template for website reports that should be global across the org
![image](https://user-images.githubusercontent.com/58074586/216401354-daeaf024-f36e-4898-ba6f-9d3d543171ba.png)

**Comment by AlexWayfer** [comment]
> > Also I'd like to see a separate issue template for frontend repo, excluding "latest release" and "safe mode" checkmarks for the application.
> 
> We have a separate template for website reports that should be global across the org ![image](https://user-images.githubusercontent.com/58074586/216401354-daeaf024-f36e-4898-ba6f-9d3d543171ba.png)

Got it. Sorry, emojis took my attention. :sweat_smile:

**Comment by confused-Techie** [comment]
I appreciate this issue, and thanks for contributing!

Hopefully all that we would need to do is set a different class when using light package themes for some of the code highlighting elements
