### ISSUE TITLE
Constrain code highlighting in README files

### ISSUE THREAD

**Issue by savetheclocktower** [pulsar-edit/package-frontend#78]
### Thanks in advance for your bug report!

- [X] Have you reproduced this issue in incognito/private browsing?
- [X] Have you made sure you issue doesn't already exist?

### Where is the URL that this occurs?

https://web.pulsar-edit.dev/packages/latex-tree

### What's your issue?

Take a look at the README on that package's page. There is a lot of _interesting_ highlighting being applied, and it's because `markdown-it-highlightjs` is being told to highlight _every_ `code` block, whether or not it exists in a `pre`. So all the inline usages of backticks are being highlighted seemingly at random from the world's most hubristic heuristic.

I haven't looked into it too deeply, but it seems like the `auto` and `inline` flags [defined here](https://github.com/pulsar-edit/package-frontend/blob/71fd8955f7ed74b4d29645cd078a308e02538381/src/utils.js#L6-L9) should be flipped to `false`, and highlighting should only happen when we're sure what the language is supposed to be.

### Which OS/Browser/Version does this happen on?

All of them.

**Comment by confused-Techie** [comment]
Appreciate the bug report, I'll try to take a look at this soon.
