### ISSUE TITLE
Repository shortcut syntax not handled correctly

### ISSUE THREAD

**Issue by Daeraxa** [pulsar-edit/package-frontend#92]
### Thanks in advance for your bug report!

- [X] Have you reproduced this issue in incognito/private browsing?
- [X] Have you made sure you issue doesn't already exist?

### Where is the URL that this occurs?

https://web.pulsar-edit.dev/packages/modular-keymaps

### What's your issue?

If you click the Github repo link it takes you to https://web.pulsar-edit.dev/packages/danielbayley/atom-modular-keymaps which obviously doesn't exist. This seems to be because the metadata is assuming github as the repo so has:
```json
    "metadata": {
      ...
      "repository": "danielbayley/atom-modular-keymaps",
```
And it seems we are expecting the full url here instead.
I propose that, for legacy packages (as we have plans to allow other forges) we need to make sure that any repository field like this is treated as a GH owner/repo format and we add the GH URL around it.

Additional info from @confused-Techie in Discord:
>  So investigating this a bit more, and it doesn't just apply to legacy packages.
According to the NPM docs https://docs.npmjs.com/cli/v9/configuring-npm/package-json#repository
This is perfectly valid, so it has to be valid for us to. That is any URL that will resolve via NPM can be used in the repository field, which includes `user/repo` (Only if on GitHub), `github:user/repo`, `gist:gistID`, `bitbucket:user/repo`, and `gitlab:user/repo`.

> Supporting this does introduce some complexity when we eventually consider adding additional VCS platforms, since it means supporting NPM conventions will again force GitHub as the default, and fallback option. Which I had hoped to avoid, but it would at least be understandable as GitHub for such a long time has been the only supported platform.

To add to the above, with the legacy packages we can be certain they are 100% github regardless of npm convention where new ones can simply be a mistake
For example we could maybe disable `user/repo` and enforce the `forge:user/repo` shortcut style
(along with the long/full style one of course).

### Which OS/Browser/Version does this happen on?

N/A

### Steps to Reproduce/Additional Details:

See full conversation at https://discord.com/channels/992103415163396136/992110095641088001/1097587445110943874

**Comment by confused-Techie** [comment]
Thanks for this, I'll see what I can do, here and on the backend, appreciate you finding this one!
