### ISSUE TITLE
Replace readme atom.io links with web.pulsar-edit.dev links

### ISSUE THREAD

**Issue by Daeraxa** [pulsar-edit/package-frontend#95]
### Have you checked for existing feature requests?

- [X] Completed

### Summary

Many packages include links to atom.io package pages which are now all dead and just direct to the sunsetting atom blog post.

The idea of this would be to dynamically replace any instance of `https://atom.io/packages/{package}` links with `https://web.pulsar-edit.dev/packages/{package}`.

e.g. Using https://web.pulsar-edit.dev/packages/minimap#available-plugins, readme has a link to `https://atom.io/packages/minimap-autohider`, this should be modified to instead direct to `https://web.pulsar-edit.dev/packages/minimap-autohider`.

We may need to consider this same function in `settings-view` to do this as well.

### What benefits does this feature provide?

No dead links in readmes requiring users to find those packages manually.

### Any alternatives?

Not really other than asking maintainers to update their docs

### Other examples:

N/A

**Comment by confused-Techie** [comment]
While we discuss this idea more on Discord, one thing I want to mention and hopefully get wider feedback on, do we want to warn when a readme is modified?

Since fixing links to github is one thing, but outright changing a link feels idk, more intrusive? Do you think we should alert the user to this? Or is it of the same vein, making a readme valid however we need to

**Comment by savetheclocktower** [comment]
I think it's good to be cautious, but I'd feel a lot different about this if those links still worked. I doubt anyone would insist that we should take the user to a URL that will just redirect to the sunset blog post.

If we really had qualms about it, we could add a parameter to the URL when it's been modified and show an inset box at the top of the page on web.pulsar-edit.dev that said something like “We rewrote this dead link to be more useful, but you can [go to the original destination](http://example.com) if you like.” But I personally don't even think that that is necessary.

**Comment by confused-Techie** [comment]
Thanks for the advice @savetheclocktower I'll keep that in mind. To be a feature if anyone has concerns or if I get really board one day.

But you are right, that I doubt anyone would have concerns about this sort of fixing of links. Just as I mentioned hit a spot for me that felt weird. Maybe at the very least a footer message at the bottom of a readme could be included (if I'd like) to say what you put above. But appreciate the feedback!

**Comment by Daeraxa** [comment]
I totally agree with the sentiment and tried to indicate that I had the same feeling on Discord:
> I don't know if this is going too far...
But I think the same as @savetheclocktower, if we were hijacking active links then it is a much bigger issue but in this case we really are taking about dead links that are completely useless.
