### ISSUE TITLE
Website throws error when searching for nothing

### ISSUE THREAD

**Issue by R0niL** [pulsar-edit/package-frontend#97]
### Thanks in advance for your bug report!

- [X] Have you reproduced this issue in incognito/private browsing?
- [X] Have you made sure you issue doesn't already exist?

### Where is the URL that this occurs?

https://web.pulsar-edit.dev/

### What's your issue?

When searching for something in the search bar but not actually putting anything but then hitting enter to search for it, will throw an error.

### Which OS/Browser/Version does this happen on?

Arch-Linux/Firefox/112.0.2(64-Bit)
Firefox Version is from Official Arch Repos

### Steps to Reproduce/Additional Details:

1. Go to https://web.pulsar-edit.dev/
2. Click the search bar to search for something but don't put anything
3. Hit enter 
4. Error will show up 
https://imgur.com/a/unjnbFD

**Comment by confused-Techie** [comment]
Thanks a ton for submitting an issue, I'll look into this one!
