### ISSUE TITLE
Website throws error when going to "Packages" in https://web.pulsar-edit.dev/

### ISSUE THREAD

**Issue by R0niL** [pulsar-edit/package-frontend#98]
### Thanks in advance for your bug report!

- [X] Have you reproduced this issue in incognito/private browsing?
- [X] Have you made sure you issue doesn't already exist?

### Where is the URL that this occurs?

https://web.pulsar-edit.dev/packages

### What's your issue?

When going to https://web.pulsar-edit.dev/ and clicking on "Packages" in the top left the website will encounter an error

### Which OS/Browser/Version does this happen on?

Arch-Linux/Firefox/112.0.2(64-Bit)
Firefox is from Official Arch Repos

### Steps to Reproduce/Additional Details:

1. Go to https://web.pulsar-edit.dev/
2. Click on "Packages" located on the top left
3. It will show error
https://imgur.com/a/unjnbFD

**Comment by Daeraxa** [comment]
This one is definitely new, I've clicked that one many times before.

**Comment by confused-Techie** [comment]
Thanks a ton for the bug report, I'll see what I can do
